-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD_LOJA
-- -----------------------------------------------------
DROP DATABASE bd_loja;
-- -----------------------------------------------------
-- Schema BD_LOJA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_LOJA` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema db_loja
-- -----------------------------------------------------
USE `BD_LOJA` ;

-- -----------------------------------------------------
-- Table `BD_LOJA`.`TB_ENDERECOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_LOJA`.`TB_ENDERECOS` (
  `END_CIDADE` VARCHAR(15) NOT NULL,
  `END_BAIRRO` VARCHAR(15) NOT NULL,
  `END_RUA` VARCHAR(45) NOT NULL,
  `END_NUMERO` INT(5) NOT NULL,
  `END_ID` INT(11) AUTO_INCREMENT,
  PRIMARY KEY (`END_ID`),
  UNIQUE INDEX `END_ID_UNIQUE` (`END_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_LOJA`.`TB_PESSOAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_LOJA`.`TB_PESSOAS` (
  `PES_NOME` VARCHAR(45) NOT NULL,
  `PES_CPF` VARCHAR(15) NOT NULL,
  `PES_EMAIL` VARCHAR(45) NOT NULL,
  `PES_DATA_NASCIMENTO` VARCHAR(10) NOT NULL,
  `PES_TELEFONE` VARCHAR(15) NOT NULL,
  `PES_ID` INT(11) AUTO_INCREMENT,
  `PES_END_ID` INT(11) NOT NULL,
  PRIMARY KEY (`PES_ID`, `PES_END_ID`),
  INDEX `fk_TB_PESSOAS_TB_ENDERECOS1_idx` (`PES_END_ID` ASC),
  CONSTRAINT `PES_END_ID`
    FOREIGN KEY (`PES_END_ID`)
    REFERENCES `BD_LOJA`.`TB_ENDERECOS` (`END_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_LOJA`.`TB_CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_LOJA`.`TB_CLIENTES` (
  `CLI_PES_ID` INT(11) AUTO_INCREMENT,
  INDEX `fk_TB_CLIENTES_TB_PESSOAS1_idx` (`CLI_PES_ID` ASC),
  PRIMARY KEY (`CLI_PES_ID`),
  UNIQUE INDEX `CLI_PES_ID_UNIQUE` (`CLI_PES_ID` ASC),
  CONSTRAINT `fk_TB_CLIENTES_TB_PESSOAS1`
    FOREIGN KEY (`CLI_PES_ID`)
    REFERENCES `BD_LOJA`.`TB_PESSOAS` (`PES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_LOJA`.`TB_FUNCIONARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_LOJA`.`TB_FUNCIONARIOS` (
  `FUN_NOME_USUARIO` VARCHAR(20) NOT NULL,
  `FUN_SENHA` VARCHAR(20) NOT NULL,
  `FUN_FUNCAO` VARCHAR(45) NOT NULL,
  `FUN_PES_ID` INT(11) AUTO_INCREMENT,
  PRIMARY KEY (`FUN_PES_ID`),
  UNIQUE INDEX `FUN_NOME_USUARIO_UNIQUE` (`FUN_NOME_USUARIO` ASC),
  UNIQUE INDEX `FUN_SENHA_UNIQUE` (`FUN_SENHA` ASC),
  INDEX `fk_TB_FUNCIONARIOS_TB_PESSOAS_idx` (`FUN_PES_ID` ASC),
  UNIQUE INDEX `FUN_PES_ID_UNIQUE` (`FUN_PES_ID` ASC),
  CONSTRAINT `fk_TB_FUNCIONARIOS_TB_PESSOAS`
    FOREIGN KEY (`FUN_PES_ID`)
    REFERENCES `BD_LOJA`.`TB_PESSOAS` (`PES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `BD_LOJA`.`TB_SETORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_LOJA`.`TB_SETORES` (
  `SET_ID` INT(11) AUTO_INCREMENT,
  `SET_SETOR` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`SET_ID`),
  UNIQUE INDEX `SET_ID_UNIQUE` (`SET_ID` ASC))
ENGINE = InnoDB;

-- DROP DATABASE bd_loja;

-- -----------------------------------------------------
-- Table `BD_LOJA`.`TB_FORNECEDORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_LOJA`.`TB_FORNECEDORES` (
  `FOR_ID` INT(11) AUTO_INCREMENT,
  `FOR_NOME_EMPRESA` VARCHAR(100) NOT NULL,
  `FOR_CNPJ` VARCHAR(20) NOT NULL,
  `FOR_SET_ID` INT(11) UNIQUE NOT NULL,
  PRIMARY KEY (`FOR_ID`, `FOR_SET_ID`),
  UNIQUE INDEX `FOR_ID_UNIQUE` (`FOR_ID` ASC),
  INDEX `fk_TB_FORNECEDORES_TB_SETORES_idx` (`FOR_SET_ID` ASC),
  CONSTRAINT `fk_TB_FORNECEDORES_TB_SETORES`
    FOREIGN KEY (`FOR_SET_ID`)
    REFERENCES `BD_LOJA`.`TB_SETORES` (`SET_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*
INDEX `fk_TB_FUNCIONARIOS_TB_PESSOAS_idx` (`FUN_PES_ID` ASC),
  UNIQUE INDEX `FUN_PES_ID_UNIQUE` (`FUN_PES_ID` ASC),
  CONSTRAINT `fk_TB_FUNCIONARIOS_TB_PESSOAS`
    FOREIGN KEY (`FUN_PES_ID`)
    REFERENCES `BD_LOJA`.`TB_PESSOAS` (`PES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
*/
-- -----------------------------------------------------
-- Table `BD_LOJA`.`TB_PROCEDIMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_LOJA`.`TB_PROCEDIMENTOS` (
  `PRO_ID` INT(11) AUTO_INCREMENT,
  `PRO_DESCRICAO` VARCHAR(200) NOT NULL,
  `PRO_VALOR` VARCHAR(45) NOT NULL,
  `PRO_EQUIPAMENTOS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PRO_ID`),
  UNIQUE INDEX `PRO_ID_UNIQUE` (`PRO_ID` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `BD_LOJA`. `BD_SOLICITACOES` (
	`SOL_ID` INT(11) AUTO_INCREMENT,
    `SOL_CLI_PES_ID` INT(11) NOT NULL,
    `SOL_FUN_PES_ID` INT(11) NOT NULL,
    `SOL_PRO_ID` INT(11) NOT NULL,
    UNIQUE INDEX `SOL_ID_UNIQUE` (`SOL_ID` ASC),
	PRIMARY KEY (`SOL_ID`, `SOL_CLI_PES_ID`, `SOL_FUN_PES_ID`, `SOL_PRO_ID`),
    INDEX `fk_TB_SOLICITACOES_TB_CLIENTES1_idx` (`SOL_CLI_PES_ID` ASC),
    INDEX `fk_TB_SOLICITACOES_TB_FUNCIONARIOS1_idx` (`SOL_FUN_PES_ID` ASC),
    INDEX `fk_TB_SOLICITACOES_TB_PROCEDIMENTOS1_idx` (`SOL_PRO_ID` ASC),
    CONSTRAINT `fk_TB_SOLICITACOES_TB_CLIENTES1`
		FOREIGN KEY (`SOL_CLI_PES_ID`)
		REFERENCES `BD_LOJA`.`TB_CLIENTES` (`CLI_PES_ID`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	CONSTRAINT `fk_TB_SOLICITACOES_TB_FUNCIONARIOS1`
		FOREIGN KEY (`SOL_FUN_PES_ID`)
		REFERENCES `BD_LOJA`.`TB_FUNCIONARIOS` (`FUN_PES_ID`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	CONSTRAINT `fk_TB_SOLICITACOES_TB_PROCEDIMENTOS1`
		FOREIGN KEY (`SOL_PRO_ID`)
		REFERENCES `BD_LOJA`.`TB_PROCEDIMENTOS` (`PRO_ID`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_LOJA`.`TB_PECAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_LOJA`.`TB_PECAS` (
  `PEC_ID` INT(11) AUTO_INCREMENT,
  `PEC_DESCRICAO` TEXT NOT NULL,
  `PEC_NUMERO_SERIE` VARCHAR(20) NOT NULL,
  `PEC_FABRICANTE` VARCHAR(45) NOT NULL,
  `PEC_GERACAO` VARCHAR(45) NOT NULL,
  `PEC_PRECO` DECIMAL NOT NULL,
  `PEC_ESTOQUE` VARCHAR(45) NOT NULL,
  `PEC_FUN_PES_ID` INT(11) NOT NULL,
  `PEC_FOR_ID` INT(11) UNIQUE NOT NULL,
  PRIMARY KEY (`PEC_ID`, `PEC_FUN_PES_ID`, `PEC_FOR_ID`),
  UNIQUE INDEX `PEC_ID_UNIQUE` (`PEC_ID` ASC),
  INDEX `fk_TB_PECAS_TB_FUNCIONARIOS1_idx` (`PEC_FUN_PES_ID` ASC),
  INDEX `fk_TB_PECAS_TB_FORNECEDORES1_idx` (`PEC_FOR_ID` ASC),
  UNIQUE INDEX `PEC_FUN_PES_ID_UNIQUE` (`PEC_FUN_PES_ID` ASC),
  CONSTRAINT `fk_TB_PECAS_TB_FUNCIONARIOS1`
    FOREIGN KEY (`PEC_FUN_PES_ID`)
    REFERENCES `BD_LOJA`.`TB_FUNCIONARIOS` (`FUN_PES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_PECAS_TB_FORNECEDORES1`
    FOREIGN KEY (`PEC_FOR_ID`)
    REFERENCES `BD_LOJA`.`TB_FORNECEDORES` (`FOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;